version: '3.1'

services:
  db:
    container_name: grineasy-mysql
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
